repos:

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.13.3
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace

- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.9.1
  hooks:
    - id: commitizen
      stages: [commit-msg]

# Security scanner for finding  vulnerabilities
- repo: https://github.com/PyCQA/bandit
  rev: '1.8.6' # TODO: Use a recent version here !
  hooks:
  - id: bandit
